### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by jitesh-prajapati123** [TwilioDevEd/conversations-demo#34]
This app is not working and gives following error.

$ **npm run start**

> conversations-demo-sdk-update@0.1.0 start D:\mydocuments\prohaat\twilio_conversations\app
> concurrently "react-scripts start" "node index.js"

[1] Application started at localhost:3002
[0] D:\mydocuments\prohaat\twilio_conversations\app\node_modules\terser-webpack-plugin\node_modules\p-limit\index.js:29
[0]             } catch {}
[0]                     ^
[0]
[0] SyntaxError: Unexpected token {
[0]     at createScript (vm.js:80:10)
[0]     at Object.runInThisContext (vm.js:139:10)
[0]     at Module._compile (module.js:616:28)
[0]     at Object.Module._extensions..js (module.js:663:10)
[0]     at Module.load (module.js:565:32)
[0]     at tryModuleLoad (module.js:505:12)
[0]     at Function.Module._load (module.js:497:3)
[0]     at Module.require (module.js:596:17)
[0]     at require (internal/module.js:11:18)
[0]     at Object.<anonymous> (D:\mydocuments\prohaat\twilio_conversations\app\node_modules\terser-webpack-plugin\dist\index.js:24:38)
[0] react-scripts start exited with code 1
[1] { error_code: 103,
[1]   status_code: 502,
[1]   msg: 'failed to start tunnel',
[1]   details:
[1]    { err: 'Only paid plans may bind custom subdomains.\nFailed to bind the custom subdomain \'ajtack\' for an unauthenticated client.\nSign up at: https://dashboard.ngrok.com/signup\n\nIf you have already signed up, make sure your authtoken is installed.\nYour authtoken is available on your dashboard: https://dashboard.ngrok.com/get-started/your-authtoken\r\n\r\nERR_NGROK_305\r\n' } }

**Comment by jefflinwood** [comment]
Hi,

This error is fixed in https://github.com/TwilioDevEd/conversations-demo/pull/38 - the application will now default to a free ngrok subdomain, unless you provide another one.
